title: "My Jekyll Theme"
baseurl: ""
url: ""
theme: null
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sass-converter
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
destination: docs
