# Site settings
title: "My Resume"
description: "A personal resume website built with Jekyll"
url: "https://yourdomain.com" # Your live site URL, e.g. https://example.com
baseurl: ""                  # The subpath of your site, e.g. /blog (leave blank if none)

# Author info
author:
  name: "Your Name"
  email: "youremail@example.com"
  twitter_username: your_twitter_handle
  github_username: your_github_handle
  linkedin_username: your_linkedin_handle

# Build settings
markdown: kramdown           # Markdown processor
theme: ""                    # Leave blank if you use your own layouts and assets
plugins:                    # List Jekyll plugins you want to use
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files and folders from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include any extra files or folders
include:
  - _pages

# Sass/SCSS settings
sass:
  style: compressed          # Options: nested, expanded, compact, compressed

# Permalinks
permalink: pretty            # /about/ instead of /about.html

# Pagination (if you want blog posts later)
paginate: 5
paginate_path: "/page:num/"

# Defaults for front matter in files
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Enable incremental build (optional)
incremental: true

# Enable future posts (optional)
future: true

